### Imports to test the conda environment

In [1]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
torch.backends.mps.is_available()

True

### Using MPS (Metal Performance Shaders) for utilizing Mac GPU
#### Note that the code in this section is specifically for checking whether it is running on a GPU or CPU
#### Instead of `torch.backends.mps.is_available()` use `torch.cuda.is_available()` for systems using Nvidia GPUs

In [3]:
if torch.backends.mps.is_available():
    print("Metal Performance Shaders are available for this system and we are using it to improve performance!")
else:
    print("Oops! Metal Performance Shaders aren't available!")

Metal Performance Shaders are available for this system and we are using it to improve performance!


In [4]:
print(f"Is MPS built? {torch.backends.mps.is_built()}")

Is MPS built? True


In [5]:
print(f"Is MPS available? {torch.backends.mps.is_available()}")

Is MPS available? True


In [6]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using {device}")

Using mps


In [7]:
x = torch.rand(size=(3,4)).to(device)

In [8]:
x

tensor([[0.1069, 0.4077, 0.5234, 0.4319],
        [0.7820, 0.9949, 0.9309, 0.0054],
        [0.2860, 0.0943, 0.7818, 0.5585]], device='mps:0')

### Creating Scalars and Vectors

In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as Python int
scalar.item()

7

In [12]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

### Creating MATRIX and TENSOR

In [15]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [17]:
# Tensors
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 56]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4, 56]]])

In [18]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [19]:
TENSOR[0], TENSOR[0][1]

(tensor([[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4, 56]]),
 tensor([3, 6, 9]))

In [20]:
TENSOR[0][0][0]

tensor(1)

In [21]:
TENSOR[0][0][1]

tensor(2)

### Creating Random Tensors
#### Why random tensors?
- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
- `Start with random nos => look at data => update the random nos => look at data => update the random nos ...`

In [22]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6788, 0.5172, 0.0668, 0.8690],
        [0.9317, 0.4923, 0.2338, 0.8474],
        [0.8352, 0.7282, 0.9893, 0.1773]])

In [23]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [24]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))  # height, width, color_channels (R, G, B)
random_image_size_tensor

tensor([[[0.6037, 0.2488, 0.3747,  ..., 0.9455, 0.8129, 0.5911],
         [0.5111, 0.2793, 0.5101,  ..., 0.6549, 0.9096, 0.2859],
         [0.1848, 0.8459, 0.6746,  ..., 0.2459, 0.5931, 0.5557],
         ...,
         [0.0262, 0.2304, 0.2962,  ..., 0.7271, 0.0339, 0.8868],
         [0.6167, 0.6264, 0.1927,  ..., 0.7007, 0.3688, 0.8348],
         [0.6827, 0.1436, 0.9985,  ..., 0.7147, 0.6702, 0.8565]],

        [[0.4616, 0.6842, 0.4523,  ..., 0.4077, 0.4759, 0.9985],
         [0.4143, 0.4041, 0.6947,  ..., 0.6115, 0.5864, 0.4255],
         [0.5155, 0.3724, 0.3577,  ..., 0.8137, 0.8224, 0.9704],
         ...,
         [0.0891, 0.6804, 0.6295,  ..., 0.6401, 0.0364, 0.6675],
         [0.5047, 0.9933, 0.1637,  ..., 0.1668, 0.1266, 0.3613],
         [0.3937, 0.8370, 0.6882,  ..., 0.5882, 0.7689, 0.1185]],

        [[0.8530, 0.0777, 0.1031,  ..., 0.0756, 0.3372, 0.1099],
         [0.6023, 0.8756, 0.6167,  ..., 0.8347, 0.0583, 0.2795],
         [0.0619, 0.4728, 0.4417,  ..., 0.0027, 0.4181, 0.

### Creating zeroes and ones tensors

In [25]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones*random_tensor == random_tensor

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [29]:
ones.dtype, zeros.dtype, random_tensor.dtype

(torch.float32, torch.float32, torch.float32)

### Creating a range of tensors and tensor-like

In [30]:
# Below range method is deprecated
# torch.range(1,10)

In [31]:
a = torch.arange(1,10)
a.dtype,a

(torch.int64, tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [32]:
step_77 = torch.arange(start=0,end=1000,step=77)
step_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [33]:
zeros_like_77 = torch.zeros_like(input=step_77)
zeros_like_77, zeros_like_77.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.int64)

In [34]:
ones_like_77 = torch.ones_like(input=step_77)
ones_like_77, ones_like_77.dtype, ones_like_77.ndim, ones_like_77.shape

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 torch.int64,
 1,
 torch.Size([13]))

In [35]:
1000 // 77

12

### Tensor Datatypes
**Note:** Tensor Datatypes are one of the big 3 errors with Pytorch and Deep Learning that we may run into
1. Tensors not on right datatype
2. Tensors not in right shape
3. Tensors not on right device

In [36]:
float_32_tensor = torch.tensor([1.0,3.0,9.0,6.8],
                               dtype=torch.float32,  # what datatype is the tensor (eg, float32 or float16)
                               device='mps',  # what device the tensor is on (eg, cpu, gpu)
                               requires_grad=False)  # whether or not to track gradients with this tensor operations 
float_32_tensor, float_32_tensor.dtype

(tensor([1.0000, 3.0000, 9.0000, 6.8000], device='mps:0'), torch.float32)

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.device, float_32_tensor.device

(tensor([1.0000, 3.0000, 9.0000, 6.8008], device='mps:0', dtype=torch.float16),
 device(type='mps', index=0),
 device(type='mps', index=0))

In [38]:
float_16_tensor * float_32_tensor

tensor([ 1.0000,  9.0000, 81.0000, 46.2453], device='mps:0')

In [39]:
float_mul_tensor = float_16_tensor * float_32_tensor
float_mul_tensor.dtype, float_mul_tensor.device

(torch.float32, device(type='mps', index=0))

In [40]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([1, 3, 9, 6], device='mps:0', dtype=torch.int32)

In [41]:
int_32_tensor * float_16_tensor

tensor([ 1.0000,  9.0000, 81.0000, 40.8125], device='mps:0',
       dtype=torch.float16)

In [44]:
float_another_mul_tensor = int_32_tensor * float_32_tensor
float_another_mul_tensor, float_another_mul_tensor.dtype

(tensor([ 1.0000,  9.0000, 81.0000, 40.8000], device='mps:0'), torch.float32)

### Getting Information From Tensors
#### To get the datatype simply type `tensor.dtype`
#### To get the shape of a tensor simply type `tensor.shape`
#### To get the device of a tensor simply type `tensor.device`

In [45]:
some_tensor = torch.rand(size=(3, 4), device='mps')
some_tensor

tensor([[0.2678, 0.7564, 0.6530, 0.2688],
        [0.7860, 0.2127, 0.3016, 0.9078],
        [0.1607, 0.7692, 0.7162, 0.0103]], device='mps:0')

In [46]:
# datatype
some_tensor.dtype

torch.float32

In [47]:
# shape and no of dimensions
some_tensor.size(), some_tensor.ndim, some_tensor.shape

(torch.Size([3, 4]), 2, torch.Size([3, 4]))

In [48]:
# device
some_tensor.device

device(type='mps', index=0)

### Manipulating Tensors (Tensor operations)
Tensor Operations include:
- Addition
- Subtractions
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [49]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3], dtype=torch.int32, device='mps')
tensor + 10

tensor([11, 12, 13], device='mps:0', dtype=torch.int32)

In [50]:
# Multiply tensor by 10 and reassign it back
tensor *= 10
tensor

tensor([10, 20, 30], device='mps:0', dtype=torch.int32)

In [51]:
# Divide tensor by 10 and reassign it back
tensor = tensor / 10
tensor, tensor.dtype

(tensor([1., 2., 3.], device='mps:0'), torch.float32)

In [52]:
# Try out Pytorch built-in functions
torch.mul(tensor, 100)

tensor([100., 200., 300.], device='mps:0')

In [53]:
tensor

tensor([1., 2., 3.], device='mps:0')

In [54]:
torch.div(tensor, 100)

tensor([0.0100, 0.0200, 0.0300], device='mps:0')

In [55]:
torch.add(tensor, 1000)

tensor([1001., 1002., 1003.], device='mps:0')

In [56]:
tensor.subtract(tensor)

tensor([0., 0., 0.], device='mps:0')

In [57]:
tensor

tensor([1., 2., 3.], device='mps:0')

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning are:
1. Element-wise multiplication
2. Matrix Multiplication

There are two main rules that need to be satisfied in order to perform matrix multiplication:
1. **Inner dimensions** must match
   * `(3, 2) @ (2, 3)` will work
   * `(3, 2) @ (3, 2)` won't work`
2. The resulting matrix has the shape of **outer dimensions**
   * `(2, 3) @ (3, 2)` => `(2, 2)`
   * `(3, 2) @ (2, 3)` => `(3, 3)`

In [58]:
tensor1 = torch.rand(size=(3,4))
tensor1

tensor([[0.5000, 0.9676, 0.8652, 0.1710],
        [0.2197, 0.5790, 0.9255, 0.6895],
        [0.4778, 0.2626, 0.6450, 0.9777]])

In [59]:
tensor2 = torch.rand(size=(4,3))
tensor2

tensor([[0.3507, 0.1795, 0.9785],
        [0.8709, 0.0628, 0.9833],
        [0.5871, 0.5504, 0.8028],
        [0.4669, 0.5238, 0.1149]])

In [60]:
tensor3 = torch.matmul(tensor1, tensor2)
tensor3

tensor([[1.6059, 0.7163, 2.1551],
        [1.4466, 0.9464, 1.6066],
        [1.2314, 0.9693, 1.3560]])

In [64]:
ten = torch.tensor([1, 2, 3], dtype=torch.int32)
ten * ten  # element wise multiplication

tensor([1, 4, 9], dtype=torch.int32)

In [65]:
torch.matmul(ten, ten)  # matrix multiplication

tensor(14, dtype=torch.int32)

In [70]:
%%time
value = 0
for i in range(len(ten)):
    value += ten[i] * ten[i]
print(value)

tensor(14, dtype=torch.int32)
CPU times: user 2.21 ms, sys: 2.02 ms, total: 4.23 ms
Wall time: 2.41 ms


In [71]:
%%time
value = torch.matmul(ten, ten)
print(value, value.device)

tensor(14, dtype=torch.int32) cpu
CPU times: user 1.19 ms, sys: 1.53 ms, total: 2.73 ms
Wall time: 1.6 ms


### One of the most common error in Deep Learning: shape errors 

In [73]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# Below line of code will give a RuntimeError as the shapes of the two tensors for multiplication do not match
# torch.mm(tensor_A, tensor_B)  # torch.mm() is same as torch.matmul() (it's an alias for writing less code)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.<br />
A **transpose** switches the axes or dimensions of a given tensor.

In [74]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [75]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [76]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [77]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum etc. (Tensor Aggregation)
**Note: the `torch.mean()` function requires a tensor of datatype float32 to work**

In [87]:
# Create a tensor
x = torch.arange(start=0, end=100, step=10)
x, x.size(), x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 torch.Size([10]),
 torch.int64)

In [84]:
# Find the min
# min = torch.min(x)
min = x.min()
min, min.dtype

(tensor(0), torch.int64)

In [85]:
# Find the max
# max = torch.max(x)
max = x.max()
max, max.dtype

(tensor(90), torch.int64)

In [92]:
# Find the mean
# mean = x.mean()
# mean
# Above lines of code won't work (not the right datatype => mean does not accept long or int64), so we need to typecast the datatype using the dtype keyword
# mean function accepts only either a floating point or a complex datatype

In [97]:
# mean = x.mean(dtype=torch.float32)
# mean = torch.mean(x, dtype=torch.float32)
mean = x.type(torch.float32).mean()
mean

tensor(45.)

In [98]:
# Find the Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [99]:
torch.median(x), x.median()

(tensor(40), tensor(40))

### Finding positional min and max using argmin and argmax

In [104]:
# argmin and argmax => index/position at which the min and max values occur in the tensor
x.argmin(), a.argmax(), x[x.argmin()], x[x.argmax()]

(tensor(0), tensor(8), tensor(0), tensor(90))

In [106]:
y = torch.arange(1, 100, step=10)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [107]:
y.argmin(), y.argmax()

(tensor(0), tensor(9))

In [108]:
y[0], y[9]

(tensor(1), tensor(91))

### Reshaping, Viewing, Stacking, Squeezing, and Unsqueezing Tensors
* Reshaping - reshapes and input tensor to a defined shape
* View - returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [114]:
x = torch.arange(1., 11.)
x, x.shape, x.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [113]:
# add an extra dimension
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]),
 2)

In [123]:
x, x_reshaped

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]))

In [126]:
# Change the view
z = x.view(5,2)
z, z.shape, z.ndim

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 6.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 2)

In [128]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[2][0] = 6
z, x

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 6.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.]))

In [131]:
# Stack tensors on top of each other
# x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.]])

In [134]:
x_v_stacked = torch.vstack([x, x, x, x])
x_v_stacked, x_v_stacked == x_stacked

(tensor([[ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.]]),
 tensor([[True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True]]))

In [133]:
x_h_stacked = torch.hstack([x, x, x, x])
x_h_stacked

tensor([ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,
         6.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,
         9., 10.,  1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.])

In [146]:
x = torch.arange(1., 11.)
x = x.reshape(1,10)
x, x.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]), 2)

In [151]:
# torch.squeeze() removes all single dimensions from a target tensor 
print("Previous tensor:")
print(x)
print(f"Previous shape: {x.shape}")
# remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x)
print("Squeezed tensor:")
print(x_squeezed)
print(f"Squeezed tensor shape: {x_squeezed.shape}")

Previous tensor:
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
Squeezed tensor:
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Squeezed tensor shape: torch.Size([10])


In [157]:
# torch.unsqueeze() adds a single dimension to a target tensor at a specific dim (dimension)
print("Previous target:")
print(x_squeezed)
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print("New tensor:")
print(x_unsqueezed)
print(f"New shape: {x_unsqueezed.shape}")

Previous target:
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
New tensor:
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [159]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order 
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color channels] 

# permute the orginal tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (2, 0, 1))  # we want color channels to be first, then height and then width
print(f"Size of original: {x_original.size()}")
print(f"Size of permuted: {x_permuted.shape}")

Size of original: torch.Size([224, 224, 3])
Size of permuted: torch.Size([3, 224, 224])


In [162]:
x_original

tensor([[[0.5794, 0.2707, 0.1589],
         [0.3553, 0.9755, 0.2418],
         [0.4787, 0.2679, 0.2225],
         ...,
         [0.9518, 0.7675, 0.6940],
         [0.0385, 0.3197, 0.2775],
         [0.3808, 0.2049, 0.8661]],

        [[0.0470, 0.0735, 0.5573],
         [0.2632, 0.7890, 0.3702],
         [0.6268, 0.1735, 0.6736],
         ...,
         [0.3458, 0.2000, 0.8444],
         [0.4477, 0.1974, 0.5353],
         [0.2676, 0.7196, 0.5361]],

        [[0.5860, 0.4519, 0.0947],
         [0.4106, 0.6249, 0.9092],
         [0.6367, 0.6177, 0.7343],
         ...,
         [0.8405, 0.7043, 0.2533],
         [0.8434, 0.9172, 0.6043],
         [0.8397, 0.7613, 0.8062]],

        ...,

        [[0.6710, 0.4934, 0.6663],
         [0.3325, 0.4705, 0.1920],
         [0.2146, 0.5091, 0.1292],
         ...,
         [0.9231, 0.6592, 0.7966],
         [0.9909, 0.9301, 0.2520],
         [0.8145, 0.1868, 0.2490]],

        [[0.5620, 0.2562, 0.0303],
         [0.7541, 0.0193, 0.6444],
         [0.

In [163]:
x_original[0, 0, 0] = 5794

In [164]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(5794.), tensor(5794.))

### Indexing (Selecting)
Indexing with Pytorch is similar to indexing with Numpy 

In [166]:
x = torch.arange(start=1, end=10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [171]:
# Let's index on our new tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [172]:
# Let's index on middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [174]:
# Let's index on the innermost bracket (dim=2)
x[0, 1, 2], x[0][2][2]

(tensor(6), tensor(9))

In [175]:
# We can also use ":" to select all of a target dimension
x[0, 1, :]

tensor([4, 5, 6])

In [176]:
# Get all values of 0th and 1st dim, but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [177]:
# Get all values of 0th dim, but only index 1 of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [178]:
# Get index 0 of 0th and 1st dim, but all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [181]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

### PyTorch and Numpy
Numpy is a very popular scientific computing library in Python. <br/>
And because of this, PyTorch has the functionality to interact with it.
* Data in numpy array, want in Pytorch tensor => `torch.from_numpy(ndarray)`
* Pytorch tensor to numpy => `torch.Tensor.numpy()`

In [185]:
array = np.arange(1., 8.)
# WARNING: when converting from numpy -> pytorch, pytorch reflects numpy's default dtype which is float64 unless specified otherwise
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [186]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [187]:
# Change the value of array, what will this do to the tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))