### Imports to test the conda environment

In [1]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
torch.backends.mps.is_available()

True

### Using MPS (Metal Performance Shaders) for utilizing Mac GPU
#### Note that the code in this section is specifically for checking whether it is running  

In [3]:
if torch.backends.mps.is_available():
    print("Metal Performance Shaders are available for this system and we are using it to improve performance!")
else:
    print("Oops! Metal Performance Shaders aren't available!")

Metal Performance Shaders are available for this system and we are using it to improve performance!


In [4]:
print(f"Is MPS built? {torch.backends.mps.is_built()}")

Is MPS built? True


In [5]:
print(f"Is MPS available? {torch.backends.mps.is_available()}")

Is MPS available? True


In [6]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using {device}")

Using mps


In [7]:
x = torch.rand(size=(3,4)).to(device)

In [8]:
x

tensor([[0.5600, 0.9395, 0.2347, 0.5851],
        [0.0945, 0.3636, 0.3196, 0.0456],
        [0.6396, 0.2068, 0.5403, 0.0642]], device='mps:0')

### Creating Scalars and Vectors

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

In [12]:
# Get tensor back as Python int
scalar.item()

7

In [13]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [14]:
vector.ndim

1

In [15]:
vector.shape

torch.Size([2])

### Creating MATRIX and TENSOR

In [27]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [28]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [30]:
# Tensors
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 56]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4, 56]]])

In [31]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [32]:
TENSOR[0], TENSOR[0][1]

(tensor([[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4, 56]]),
 tensor([3, 6, 9]))

In [33]:
TENSOR[0][0][0]

tensor(1)

In [34]:
TENSOR[0][0][1]

tensor(2)

### Creating Random Tensors
#### Why random tensors?
- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
- `Start with random nos => look at data => update the random nos => look at data => update the random nos ...`

In [ ]:
# Create a random tensor
# 1:39:31