### Imports to test the conda environment

In [1]:
import torch
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
torch.backends.mps.is_available()

True

### Using MPS (Metal Performance Shaders) for utilizing Mac GPU
#### Note that the code in this section is specifically for checking whether it is running on a GPU or CPU
#### Instead of `torch.backends.mps.is_available()` use `torch.cuda.is_available()` for systems using Nvidia GPUs

In [3]:
if torch.backends.mps.is_available():
    print("Metal Performance Shaders are available for this system and we are using it to improve performance!")
else:
    print("Oops! Metal Performance Shaders aren't available!")

Metal Performance Shaders are available for this system and we are using it to improve performance!


In [4]:
print(f"Is MPS built? {torch.backends.mps.is_built()}")

Is MPS built? True


In [5]:
print(f"Is MPS available? {torch.backends.mps.is_available()}")

Is MPS available? True


In [6]:
device = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using {device}")

Using mps


In [7]:
x = torch.rand(size=(3,4)).to(device)

In [8]:
x

tensor([[0.9897, 0.4534, 0.2045, 0.2258],
        [0.4348, 0.7880, 0.7695, 0.9900],
        [0.0504, 0.6211, 0.1999, 0.7149]], device='mps:0')

### Creating Scalars and Vectors

In [9]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [10]:
scalar.ndim

0

In [11]:
# Get tensor back as Python int
scalar.item()

7

In [12]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

### Creating MATRIX and TENSOR

In [15]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [17]:
# Tensors
TENSOR = torch.tensor([[[1, 2, 3],
                       [3, 6, 9],
                       [2, 4, 56]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4, 56]]])

In [18]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [19]:
TENSOR[0], TENSOR[0][1]

(tensor([[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4, 56]]),
 tensor([3, 6, 9]))

In [20]:
TENSOR[0][0][0]

tensor(1)

In [21]:
TENSOR[0][0][1]

tensor(2)

### Creating Random Tensors
#### Why random tensors?
- Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data
- `Start with random nos => look at data => update the random nos => look at data => update the random nos ...`

In [22]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.3704, 0.3976, 0.7295, 0.6906],
        [0.0994, 0.2495, 0.8552, 0.4103],
        [0.1878, 0.8833, 0.3063, 0.4573]])

In [23]:
random_tensor.ndim, random_tensor.shape

(2, torch.Size([3, 4]))

In [24]:
# Create a random tensor with a similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224))  # height, width, color_channels (R, G, B)
random_image_size_tensor

tensor([[[0.4169, 0.7871, 0.1354,  ..., 0.9015, 0.4159, 0.9461],
         [0.5490, 0.7804, 0.6586,  ..., 0.2555, 0.0261, 0.1514],
         [0.7321, 0.6204, 0.2681,  ..., 0.3313, 0.0168, 0.8562],
         ...,
         [0.4931, 0.3309, 0.7482,  ..., 0.0800, 0.2093, 0.9108],
         [0.9082, 0.0161, 0.7472,  ..., 0.0468, 0.6335, 0.3757],
         [0.4910, 0.9575, 0.4729,  ..., 0.1730, 0.8591, 0.1505]],

        [[0.3891, 0.9254, 0.5381,  ..., 0.4580, 0.3809, 0.8713],
         [0.8302, 0.9327, 0.1174,  ..., 0.2747, 0.2967, 0.1782],
         [0.7567, 0.5474, 0.9281,  ..., 0.6253, 0.8674, 0.7973],
         ...,
         [0.3062, 0.1855, 0.0898,  ..., 0.4181, 0.7184, 0.6944],
         [0.2851, 0.7456, 0.0183,  ..., 0.2270, 0.8886, 0.5008],
         [0.2767, 0.9496, 0.1634,  ..., 0.2822, 0.0423, 0.7861]],

        [[0.0536, 0.2219, 0.4693,  ..., 0.7994, 0.7010, 0.3359],
         [0.8363, 0.0013, 0.3186,  ..., 0.2077, 0.2424, 0.1557],
         [0.2419, 0.6566, 0.5390,  ..., 0.4653, 0.6090, 0.

### Creating zeroes and ones tensors

In [25]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# Create tensor of ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones*random_tensor == random_tensor

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [29]:
ones.dtype, zeros.dtype, random_tensor.dtype

(torch.float32, torch.float32, torch.float32)

### Creating a range of tensors and tensor-like

In [30]:
# Below range method is deprecated
# torch.range(1,10)

In [31]:
a = torch.arange(1,10)
a.dtype,a

(torch.int64, tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [32]:
step_77 = torch.arange(start=0,end=1000,step=77)
step_77

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [33]:
zeros_like_77 = torch.zeros_like(input=step_77)
zeros_like_77, zeros_like_77.dtype

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]), torch.int64)

In [34]:
ones_like_77 = torch.ones_like(input=step_77)
ones_like_77, ones_like_77.dtype, ones_like_77.ndim, ones_like_77.shape

(tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]),
 torch.int64,
 1,
 torch.Size([13]))

In [35]:
1000 // 77

12

### Tensor Datatypes
**Note:** Tensor Datatypes are one of the big 3 errors with Pytorch and Deep Learning that we may run into
1. Tensors not on right datatype
2. Tensors not in right shape
3. Tensors not on right device

In [36]:
float_32_tensor = torch.tensor([1.0,3.0,9.0,6.8],
                               dtype=torch.float32,  # what datatype is the tensor (eg, float32 or float16)
                               device='mps',  # what device the tensor is on (eg, cpu, gpu)
                               requires_grad=False)  # whether or not to track gradients with this tensor operations 
float_32_tensor, float_32_tensor.dtype

(tensor([1.0000, 3.0000, 9.0000, 6.8000], device='mps:0'), torch.float32)

In [37]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.device, float_32_tensor.device

(tensor([1.0000, 3.0000, 9.0000, 6.8008], device='mps:0', dtype=torch.float16),
 device(type='mps', index=0),
 device(type='mps', index=0))

In [38]:
float_16_tensor * float_32_tensor

tensor([ 1.0000,  9.0000, 81.0000, 46.2453], device='mps:0')

In [39]:
float_mul_tensor = float_16_tensor * float_32_tensor
float_mul_tensor.dtype, float_mul_tensor.device

(torch.float32, device(type='mps', index=0))

In [40]:
int_32_tensor = float_32_tensor.type(torch.int32)
int_32_tensor

tensor([1, 3, 9, 6], device='mps:0', dtype=torch.int32)

In [41]:
int_32_tensor * float_16_tensor

tensor([ 1.0000,  9.0000, 81.0000, 40.8125], device='mps:0',
       dtype=torch.float16)

In [42]:
float_another_mul_tensor = int_32_tensor * float_32_tensor
float_another_mul_tensor, float_another_mul_tensor.dtype

(tensor([ 1.0000,  9.0000, 81.0000, 40.8000], device='mps:0'), torch.float32)

### Getting Information From Tensors
#### To get the datatype simply type `tensor.dtype`
#### To get the shape of a tensor simply type `tensor.shape`
#### To get the device of a tensor simply type `tensor.device`

In [43]:
some_tensor = torch.rand(size=(3, 4), device='mps')
some_tensor

tensor([[0.8772, 0.6057, 0.9304, 0.0986],
        [0.3825, 0.1345, 0.8387, 0.4931],
        [0.8424, 0.1803, 0.3098, 0.9477]], device='mps:0')

In [44]:
# datatype
some_tensor.dtype

torch.float32

In [45]:
# shape and no of dimensions
some_tensor.size(), some_tensor.ndim, some_tensor.shape

(torch.Size([3, 4]), 2, torch.Size([3, 4]))

In [46]:
# device
some_tensor.device

device(type='mps', index=0)

### Manipulating Tensors (Tensor operations)
Tensor Operations include:
- Addition
- Subtractions
- Multiplication (element-wise)
- Division
- Matrix Multiplication

In [47]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3], dtype=torch.int32, device='mps')
tensor + 10

tensor([11, 12, 13], device='mps:0', dtype=torch.int32)

In [48]:
# Multiply tensor by 10 and reassign it back
tensor *= 10
tensor

tensor([10, 20, 30], device='mps:0', dtype=torch.int32)

In [49]:
# Divide tensor by 10 and reassign it back
tensor = tensor / 10
tensor, tensor.dtype

(tensor([1., 2., 3.], device='mps:0'), torch.float32)

In [50]:
# Try out Pytorch built-in functions
torch.mul(tensor, 100)

tensor([100., 200., 300.], device='mps:0')

In [51]:
tensor

tensor([1., 2., 3.], device='mps:0')

In [52]:
torch.div(tensor, 100)

tensor([0.0100, 0.0200, 0.0300], device='mps:0')

In [53]:
torch.add(tensor, 1000)

tensor([1001., 1002., 1003.], device='mps:0')

In [54]:
tensor.subtract(tensor)

tensor([0., 0., 0.], device='mps:0')

In [55]:
tensor

tensor([1., 2., 3.], device='mps:0')

### Matrix Multiplication
Two main ways of performing multiplication in neural networks and deep learning are:
1. Element-wise multiplication
2. Matrix Multiplication

There are two main rules that need to be satisfied in order to perform matrix multiplication:
1. **Inner dimensions** must match
   * `(3, 2) @ (2, 3)` will work
   * `(3, 2) @ (3, 2)` won't work`
2. The resulting matrix has the shape of **outer dimensions**
   * `(2, 3) @ (3, 2)` => `(2, 2)`
   * `(3, 2) @ (2, 3)` => `(3, 3)`

In [56]:
tensor1 = torch.rand(size=(3,4))
tensor1

tensor([[0.9066, 0.8338, 0.0409, 0.5889],
        [0.3928, 0.3551, 0.1626, 0.7931],
        [0.0115, 0.6469, 0.1099, 0.4169]])

In [57]:
tensor2 = torch.rand(size=(4,3))
tensor2

tensor([[0.9852, 0.7669, 0.2201],
        [0.2519, 0.7007, 0.7178],
        [0.6732, 0.8972, 0.9946],
        [0.7435, 0.9135, 0.4166]])

In [58]:
tensor3 = torch.matmul(tensor1, tensor2)
tensor3

tensor([[1.5686, 1.8541, 1.0840],
        [1.1756, 1.4205, 0.8335],
        [0.5583, 0.9416, 0.7499]])

In [59]:
ten = torch.tensor([1, 2, 3], dtype=torch.int32)
ten * ten  # element wise multiplication

tensor([1, 4, 9], dtype=torch.int32)

In [60]:
torch.matmul(ten, ten)  # matrix multiplication

tensor(14, dtype=torch.int32)

In [61]:
%%time
value = 0
for i in range(len(ten)):
    value += ten[i] * ten[i]
print(value)

tensor(14, dtype=torch.int32)
CPU times: user 546 μs, sys: 743 μs, total: 1.29 ms
Wall time: 1.57 ms


In [62]:
%%time
value = torch.matmul(ten, ten)
print(value, value.device)

tensor(14, dtype=torch.int32) cpu
CPU times: user 240 μs, sys: 157 μs, total: 397 μs
Wall time: 272 μs


### One of the most common error in Deep Learning: shape errors 

In [63]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])
# Below line of code will give a RuntimeError as the shapes of the two tensors for multiplication do not match
# torch.mm(tensor_A, tensor_B)  # torch.mm() is same as torch.matmul() (it's an alias for writing less code)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.<br />
A **transpose** switches the axes or dimensions of a given tensor.

In [64]:
tensor_B, tensor_B.T

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 tensor([[ 7,  8,  9],
         [10, 11, 12]]))

In [65]:
tensor_B.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [66]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [67]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### Finding the min, max, mean, sum etc. (Tensor Aggregation)
**Note: the `torch.mean()` function requires a tensor of datatype float32 to work**

In [68]:
# Create a tensor
x = torch.arange(start=0, end=100, step=10)
x, x.size(), x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 torch.Size([10]),
 torch.int64)

In [69]:
# Find the min
# min = torch.min(x)
min = x.min()
min, min.dtype

(tensor(0), torch.int64)

In [70]:
# Find the max
# max = torch.max(x)
max = x.max()
max, max.dtype

(tensor(90), torch.int64)

In [71]:
# Find the mean
# mean = x.mean()
# mean
# Above lines of code won't work (not the right datatype => mean does not accept long or int64), so we need to typecast the datatype using the dtype keyword
# mean function accepts only either a floating point or a complex datatype

In [72]:
# mean = x.mean(dtype=torch.float32)
# mean = torch.mean(x, dtype=torch.float32)
mean = x.type(torch.float32).mean()
mean

tensor(45.)

In [73]:
# Find the Sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [74]:
torch.median(x), x.median()

(tensor(40), tensor(40))

### Finding positional min and max using argmin and argmax

In [75]:
# argmin and argmax => index/position at which the min and max values occur in the tensor
x.argmin(), a.argmax(), x[x.argmin()], x[x.argmax()]

(tensor(0), tensor(8), tensor(0), tensor(90))

In [76]:
y = torch.arange(1, 100, step=10)
y

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [77]:
y.argmin(), y.argmax()

(tensor(0), tensor(9))

In [78]:
y[0], y[9]

(tensor(1), tensor(91))

### Reshaping, Viewing, Stacking, Squeezing, and Unsqueezing Tensors
* Reshaping - reshapes and input tensor to a defined shape
* View - returns a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [79]:
x = torch.arange(1., 11.)
x, x.shape, x.ndim

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 1)

In [80]:
# add an extra dimension
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape, x_reshaped.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]),
 2)

In [81]:
x, x_reshaped

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]))

In [82]:
# Change the view
z = x.view(5,2)
z, z.shape, z.ndim

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]),
 2)

In [83]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[2][0] = 6
z, x

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 6.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 tensor([ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.]))

In [84]:
# Stack tensors on top of each other
# x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.]])

In [85]:
x_v_stacked = torch.vstack([x, x, x, x])
x_v_stacked, x_v_stacked == x_stacked

(tensor([[ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.]]),
 tensor([[True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True],
         [True, True, True, True, True, True, True, True, True, True]]))

In [86]:
x_h_stacked = torch.hstack([x, x, x, x])
x_h_stacked

tensor([ 1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,
         6.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,
         9., 10.,  1.,  2.,  3.,  4.,  6.,  6.,  7.,  8.,  9., 10.])

In [87]:
x = torch.arange(1., 11.)
x = x.reshape(1,10)
x, x.ndim

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]), 2)

In [88]:
# torch.squeeze() removes all single dimensions from a target tensor 
print("Previous tensor:")
print(x)
print(f"Previous shape: {x.shape}")
# remove extra dimensions from x_reshaped
x_squeezed = torch.squeeze(x)
print("Squeezed tensor:")
print(x_squeezed)
print(f"Squeezed tensor shape: {x_squeezed.shape}")

Previous tensor:
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])
Previous shape: torch.Size([1, 10])
Squeezed tensor:
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Squeezed tensor shape: torch.Size([10])


In [89]:
# torch.unsqueeze() adds a single dimension to a target tensor at a specific dim (dimension)
print("Previous target:")
print(x_squeezed)
print(f"Previous shape: {x_squeezed.shape}")

# add extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print("New tensor:")
print(x_unsqueezed)
print(f"New shape: {x_unsqueezed.shape}")

Previous target:
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
Previous shape: torch.Size([10])
New tensor:
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])
New shape: torch.Size([10, 1])


In [90]:
# torch.permute() rearranges the dimensions of a target tensor in a specified order 
x_original = torch.rand(size=(224, 224, 3))  # [height, width, color channels] 

# permute the orginal tensor to rearrange the axis (or dim) order
x_permuted = torch.permute(x_original, (2, 0, 1))  # we want color channels to be first, then height and then width
print(f"Size of original: {x_original.size()}")
print(f"Size of permuted: {x_permuted.shape}")

Size of original: torch.Size([224, 224, 3])
Size of permuted: torch.Size([3, 224, 224])


In [91]:
x_original

tensor([[[0.2596, 0.4300, 0.5594],
         [0.0066, 0.2661, 0.1674],
         [0.1085, 0.4798, 0.5917],
         ...,
         [0.4343, 0.8138, 0.2029],
         [0.5538, 0.3319, 0.7467],
         [0.5398, 0.6108, 0.6696]],

        [[0.3280, 0.4116, 0.5747],
         [0.0207, 0.5035, 0.4899],
         [0.1617, 0.1149, 0.2835],
         ...,
         [0.6379, 0.7139, 0.8716],
         [0.0690, 0.2961, 0.4525],
         [0.6557, 0.4899, 0.5720]],

        [[0.0782, 0.1770, 0.5671],
         [0.5447, 0.2187, 0.5821],
         [0.7875, 0.2080, 0.5751],
         ...,
         [0.1659, 0.1929, 0.5209],
         [0.4919, 0.5379, 0.7947],
         [0.9284, 0.3257, 0.8464]],

        ...,

        [[0.5578, 0.5662, 0.1272],
         [0.8086, 0.5570, 0.0402],
         [0.9345, 0.9793, 0.0226],
         ...,
         [0.3210, 0.7814, 0.6712],
         [0.3666, 0.9502, 0.7682],
         [0.3343, 0.8653, 0.7308]],

        [[0.8575, 0.3845, 0.6697],
         [0.6101, 0.2841, 0.8973],
         [0.

In [92]:
x_original[0, 0, 0] = 5794

In [93]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(5794.), tensor(5794.))

### Indexing (Selecting)
Indexing with Pytorch is similar to indexing with Numpy 

In [94]:
x = torch.arange(start=1, end=10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [95]:
# Let's index on our new tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [96]:
# Let's index on middle bracket (dim=1)
x[0, 0]

tensor([1, 2, 3])

In [97]:
# Let's index on the innermost bracket (dim=2)
x[0, 1, 2], x[0][2][2]

(tensor(6), tensor(9))

In [98]:
# We can also use ":" to select all of a target dimension
x[0, 1, :]

tensor([4, 5, 6])

In [99]:
# Get all values of 0th and 1st dim, but only index 1 of 2nd dim
x[:, :, 1]

tensor([[2, 5, 8]])

In [100]:
# Get all values of 0th dim, but only index 1 of 1st and 2nd dim
x[:, 1, 1]

tensor([5])

In [101]:
# Get index 0 of 0th and 1st dim, but all values of 2nd dim
x[0, 0, :]

tensor([1, 2, 3])

In [102]:
# Index on x to return 3, 6, 9
x[0, :, 2]

tensor([3, 6, 9])

### PyTorch and Numpy
Numpy is a very popular scientific computing library in Python. <br/>
And because of this, PyTorch has the functionality to interact with it.
* Data in numpy array, want in Pytorch tensor => `torch.from_numpy(ndarray)`
* Pytorch tensor to numpy => `torch.Tensor.numpy()`

In [103]:
array = np.arange(1., 8.)
# WARNING: when converting from numpy -> pytorch, pytorch reflects numpy's default dtype which is float64 unless specified otherwise
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [104]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [105]:
# Change the value of array, what will this do to the tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [114]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
# Change the tensor, what happens to the numpy array?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take out the random from random)
In short how a neural network Learns:<br />
`start with random nos => tensor operations => update random nos to try and make them better representations of the data => again ...` <br />
To reduce the randomness in neural networks and Pytorch, comes the concept of **random seed**<br />
Essentially what the random seed does is "flavor" the randomness.

In [116]:
# Create two random tensors 
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2651, 0.1850, 0.0774, 0.0893],
        [0.5713, 0.7317, 0.1043, 0.2575],
        [0.3605, 0.7210, 0.6769, 0.4966]])
tensor([[0.4391, 0.9958, 0.7561, 0.4034],
        [0.0123, 0.0866, 0.1295, 0.2616],
        [0.8562, 0.5262, 0.0838, 0.3040]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [123]:
# Let's make some random but reproducible tensors 
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and Pytorch objects on the GPUs (and making faster computations)
GPUs = faster computation on numbers, thanks to MPS + Apple hardware + PyTorch working behind the scenes to make everything fast.<br />
**Getting a GPU**
- Use Google Colab for a free GPU
- Use your own GPU - requires investment in hardware
- Use Cloud Computing like GCP, AWS, Azure, these services allow us to rent computers on the cloud and access them

In [125]:
# Check for GPU access with Pytorch
torch.backends.mps.is_built(), torch.backends.mps.is_available()

(True, True)

For PyTorch since it's capable of running compute on GPU or CPU, it's best practice to setup device agnostic code since there is no guarantee that the GPU will be available for us all the time.<br />
E.g, run on GPU if available else default to CPU

In [126]:
# Setup device agnostic code 
device = "mps" if torch.backends.mps.is_available() else "cpu"
device

'mps'

In [127]:
# Count the number of devices
torch.mps.device_count()

1

### Putting tensors and models on the GPU
The reason we want our tensors/models on GPU is because using a GPU results in faster computation

In [128]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [129]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')

### Moving tensors back to the CPU
If tensor is on GPU, it can't be tranformed into a numpy array as numpy only works on CPU

In [131]:
# Below line of code will give us a TypeError as our tensor is on GPU and numpy arrays only work on CPU
# tensor_on_gpu.numpy()

In [133]:
# to fix the GPU tensor with NumPy issue, we can first set it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [134]:
tensor_on_gpu

tensor([1, 2, 3], device='mps:0')